controllers/CatalogController.php
<?php

namespace app\controllers;

use app\models\CatalogItems;
use app\models\CatalogTemplates;
use app\models\Items;
use Yii;
use app\models\CatalogRu;
use app\models\CatalogSearchRu;
use yii\base\Exception;
use yii\web\Controller;
use yii\web\Cookie;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\filters\AccessControl;

/**
 * CatalogController implements the CRUD actions for CatalogRu model.
 */
class CatalogController extends Controller
{

    public $defaultAction='no';

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['admin', 'create', 'update', 'update-parent', 'update-order', 'delete', 'index', 'get-item', 'view', 'items'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'get-item', 'view', 'items'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all CatalogRu models.
     * @return mixed
     */
    public function actionAdmin()
    {
        $searchModel = new CatalogSearchRu();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('admin', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionItems() {
        $id = Yii::$app->request->get('id');
        /** @var Items $model */
        $model = Items::find()->where(['fiitem_id' => (int)$id])->one();
        if(empty($model)) {
           throw new Exception('Can\'t find item');
        }
        $catalogItem = CatalogItems::findOne(['fiitem_id' => (int)$model->fiitem_id]);
        $catalog = $this->findModel($catalogItem->ficatalog_id);

	$cat = ((int)$catalog->fivisible ? (int)$catalog->ficatalog_id : (int)$catalog->fiparent_catalog_id);
        $catalogs = Yii::$app->db->createCommand('SELECT
                                                c3.ficatalog_id as general_id,
                                              c3.fsname as general_name,
                                                c2.ficatalog_id as middle_id,
                                              c2.fsname as middle_name,
                                                c1.ficatalog_id as low_id,
                                              c1.fsname as low_name
                                            FROM
                                                catalog_ru c1
                                            LEFT JOIN catalog_ru c2 ON c2.ficatalog_id = c1.fiparent_catalog_id
                                            LEFT JOIN catalog_ru c3 ON c3.ficatalog_id = c2.fiparent_catalog_id
                                            WHERE
                                                c1.ficatalog_id = :catalogid',['catalogid' => (int)$cat])->queryOne();

        return $this->render('one-view.php', [
          'item' => $model,
          'catalog' => $catalog,
          'breadCrumbs' => $catalogs,
        ]);
    }

    /**
     * Lists all CatalogRu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $viewTemplate = '';
        $searchModel = new CatalogSearchRu();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $catalog = Yii::$app->request->get('cat');
        if(empty($catalog)) {
            $catalog = Yii::$app->db->createCommand('SELECT ficatalog_id from catalog_ru where fiparent_Catalog_id is null or fiparent_catalog_id = "" limit 1')->queryOne();
            $catalog = (int) $catalog['ficatalog_id'];
        }

        $catalogs = Yii::$app->db->createCommand('SELECT
                                                c3.ficatalog_id as general_id,
                                              c3.fsname as general_name,
                                                c2.ficatalog_id as middle_id,
                                              c2.fsname as middle_name,
                                                c1.ficatalog_id as low_id,
                                              c1.fsname as low_name
                                            FROM
                                                catalog_ru c1
                                            LEFT JOIN catalog_ru c2 ON c2.ficatalog_id = c1.fiparent_catalog_id
                                            LEFT JOIN catalog_ru c3 ON c3.ficatalog_id = c2.fiparent_catalog_id
                                            WHERE
                                                c1.ficatalog_id = :catalogid',['catalogid' => (int)$catalog])->queryOne();

        $level = 0;
        if(!empty($catalogs['general_id']) && !empty($catalogs['middle_id'])) {
            $level = 2;
        }
        elseif(!empty($catalogs['middle_id']) && empty($catalogs['general_id'])) {
            $level = 1;
        }

        $podcats = Yii::$app->db->createCommand('SELECT count(*) as `count` from catalog_ru
                                            WHERE
                                                fiparent_catalog_id = :catalogid AND fishow_with_items <> 1',['catalogid' => (int)$catalog])->queryOne();

        if(!$podcats['count']) {
            $level = 2;
        }

        $current = CatalogRu::find()->where(['ficatalog_id' => (int)$catalog])->andWhere(['fivisible' => 1])->one();

        if($current) {
          $this->view->seoFields = @$current->fsseo;
        }

        $params = [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
            'level'        => $level,
            'breadCrumbs'  => $catalogs,
            'subcat'       => $catalog,
        ];

        if(!empty($current->fstemplate_code)) {
            $template = CatalogTemplates::find()->where(['fstemplate_code' => $current->fstemplate_code])->one();
            if(!empty($template)) {
                $params = array_merge($params, ['template' => $template->fstemplate_text]);
                return $this->render('custom_template', $params);
            }
        }

        if(1/*Yii::$app->request->get('view') == 'new' || Yii::$app->request->cookies->has('view')*/) {
            if($level == 2) {
                $viewTemplate = 'new-';
            }
            // Yii::$app->response->cookies->add(new Cookie(['name' => 'view', 'value' => 'new']));

            if($catalog && !$current) {
                $current = CatalogRu::find()->where(['ficatalog_id' => (int)$catalog])->one();
                if(!empty($current)) {
                    $current = CatalogRu::find()->where(['ficatalog_id' => (int)$current->fiparent_catalog_id])->one();
                }
                $this->view->seoFields = @$current->fsseo;
                $params['subcat'] = (int)$current->ficatalog_id;
                $catalogs = Yii::$app->db->createCommand('SELECT
                                                c3.ficatalog_id as general_id,
                                              c3.fsname as general_name,
                                                c2.ficatalog_id as middle_id,
                                              c2.fsname as middle_name,
                                                c1.ficatalog_id as low_id,
                                              c1.fsname as low_name
                                            FROM
                                                catalog_ru c1
                                            LEFT JOIN catalog_ru c2 ON c2.ficatalog_id = c1.fiparent_catalog_id
                                            LEFT JOIN catalog_ru c3 ON c3.ficatalog_id = c2.fiparent_catalog_id
                                            WHERE
                                                c1.ficatalog_id = :catalogid',['catalogid' => (int)$current->ficatalog_id])->queryOne();
                $params['breadCrumbs'] = $catalogs;
            }
        }

        if(Yii::$app->request->get('view') == 'old') {
            Yii::$app->response->cookies->remove('view');
            $viewTemplate = '';
        }

        return $this->render('catalog-index-level-' . $viewTemplate . (int) $level, $params);
    }

     public function actionGetItem() {
        $id = Yii::$app->request->post('id', (int)Yii::$app->request->get('id'));
	return $this->redirect(['catalog/items', 'id' => (int) $id]);
        $params = Yii::$app->db->createCommand('SELECT
                                                    pc.fsparam_name as `name`,
                                                  pv.fsparam_value as `value`
                                                FROM
                                                    params_values pv
                                                LEFT JOIN params_cat pc ON pv.fiparam_id = pc.fiparam_id
                                                WHERE
                                                    pv.fiitem_id = :fiitemid
                                                ORDER BY
                                                    (CASE WHEN pv.fiorder IS NULL then 99999 ELSE pv.fiorder END)', ['fiitemid' => (int)$id])->queryAll();
        $itemInfo = Items::find()->where(['fiitem_id' => (int) $id])->one();
        if(Yii::$app->request->isAjax) {
            return $this->renderAjax('item-props-ajax', ['params' => $params, 'itemInfo' => $itemInfo]);
        }
        else {

views/catalog/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CatalogSearchRu */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="catalog-ru-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ficatalog_id') ?>

    <?= $form->field($model, 'fsname') ?>

    <?= $form->field($model, 'fiparent_catalog_id') ?>

    <?= $form->field($model, 'fscatalog_img') ?>

    <?= $form->field($model, 'fscatalog_text') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/catalog/_test-form.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\Pjax;
use kartik\typeahead\Typeahead;

$data = isset($data) ? $data : [];
?>
<div class="col-xs-12 padding-none filter" style="margin-bottom: 10px;">
    <style>
        .form-control.tt-input{ 
            background: #fff!important;; 
            border: 1px solid #CCCCCC!important;
        }
    </style>
<?php Pjax::begin(['enablePushState' => false]); ?>
    <h4>Поиск по аналогам</h4>
    <p>Корректно введите в строке поиска название аналога</p>
    <h5><?=Yii::$app->request->post('q')?></h5>
    <?=Html::beginForm(['test/item'], 'post', ['data-pjax' => '', 'class' => 'form-inline'])?>
        <?php /*echo Html::textInput('q', Yii::$app->request->post('q'), []);*/ ?>
        <div class="form-group">
        <?=Typeahead::widget([
            'name' => 'q',
            'dataset' => [
                [
                    'datumTokenizer' => "Bloodhound.tokenizers.obj.whitespace('value')",
                    'display' => 'value',
                    'remote' => [
                        'url' => Url::to(['test/suggest']) . '?q=%QUERY',
                        'wildcard' => '%QUERY'
                    ],
                    'limit' => 10
                ]
            ],
            'options' => ['class' => 'form-control'],
            'pluginOptions' => ['highlight'=>true],
        ])?>
        </div>
        <?=Html::submitButton('Поиск', ['class' => 'btn btn-default', 'style' => 'margin-top: 3px;'])?>
    <?=Html::endForm()?>
    <ul>
        <?php foreach ($data as $item): ?>
        <?php $url = str_replace('fif.by', 'tde-fif.ru', $item['url']) ?>
        <li><a href="<?=$url?>"><?=$item['fsitem_name']?></a></li>
        <?php endforeach;?>
    </ul>
<?php Pjax::end(); ?>
</div>

views/catalog/catalog-index-level-0.php
<?php
//require_once 'catalog-index-level-0_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'catalog-index-1']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>

views/catalog/catalog-index-level-0_old.php
<?php

use yii\helpers\Html;
use app\models\CatalogRu;

$parent = [];
$parentsQeury = CatalogRu::find()->where(['fiparent_catalog_id' => null])->andWhere(['fivisible' => 1])->orWhere(['fiparent_catalog_id'=>''])->orderBy('fiorder')->all();
/** @var CatalogRu $parents */
foreach($parentsQeury as $parents) {
    $translates = json_decode($parents->translates, true);
    $parent[] = [
        'id' => $parents->ficatalog_id,
        'name' => $translates['values'][Yii::$app->language]['fsname'],
        'big-image' => $parents->fsbigicon,
        'link' => $parents->fslink,
        'subcat' => [],
    ];
}

$all = CatalogRu::find()->where(['fivisible' => 1])->orderBy('fiorder')->all();
/** @var CatalogRU $row */
foreach($all as $row) {
    foreach($parent as $index => $category) {
        if($category['id'] == $row->fiparent_catalog_id) {
            $translates = json_decode($row->translates, true);
            $parent[$index]['subcat'][] = [
                'id' => $row->ficatalog_id,
                'name' => $translates['values'][Yii::$app->language]['fsname'],
                'subcat' => [],
                'icon' => $row->fsicon];
        }
    }
}

foreach($all as $row) {
    foreach($parent as $indcat => $category) {
        foreach($category['subcat'] as $index => $subcat) {
            if($subcat['id'] == $row->fiparent_catalog_id) {
                $translates = json_decode($row->translates, true);
                $parent[$indcat]['subcat'][$index]['subcat'][] = [
                    'id' => $row->ficatalog_id,
                    'name' => $translates['values'][Yii::$app->language]['fsname'],
                    'subcat' => []];
            }
        }
    }
}

$activeCat = Yii::$app->request->get('cat');
if(empty($activeCat)) {
    $activeCat = $parent[0]['id'];
}

/* @var $this yii\web\View */
/* @var $searchModel app\models\CatalogSearchRu */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*$this->title = Yii::t('app', 'app.cat');*/

//print_r($parent);

?>
<div class="catalog-general">
    <div class="col-xs-12 padding-none info-block">
        <div class="col-xs-4 padding-none">
            <span class="title"><?php echo Yii::t('app', 'catalog.title') ?></span>
        </div>
        <div class="col-xs-4 padding-none">
            <?php

            $filename = '';
            $scan = scandir(__DIR__ . '/../../web', SCANDIR_SORT_DESCENDING);
            foreach($scan as $file) {
                if(strpos($file, 'catalog_') === 0) {
                    $filename = $file;
                    break;
                }
            }

            ?>
            <div class="border">
                <div class="file">
                    <a href="<?php echo Yii::$app->request->baseUrl . '/' . $filename ?>">
                        <?php echo Html::img(Yii::$app->request->baseUrl . '/image/site/file.png') ?>
                    </a>
                </div>
                <div class="file-info">
                    <a href="<?php echo Yii::$app->request->baseUrl . '/' . $filename ?>"><span><?php echo Yii::t('app', 'catalog.all.production') ?></span></a><br/>
                    <span class="gray">(<?php echo strlen($filename) ? 'pdf, ' . round(filesize(__DIR__ . '/../../web/' . $filename)/1024/1024, 0) . ' ' . Yii::t('app', 'catalog.mb') : 'pdf, 27 мб' ?>)</span>
                </div>
            </div>
        </div>
        <div class="col-xs-4 padding-none">
            <div class="border last external">
                <span class="dashed-link"><a href=""><?php echo Yii::t('app', 'catalog.functional') ?></a></span><br/>
                <span class="dashed-link"><a href=""><?php echo Yii::t('app', 'catalog.analog') ?></a></span>
            </div>
        </div>
    </div>
    <?php echo $this->render('catalog-menu', ['catalogs' => $parent, 'active' => $activeCat]); ?>
    <div class="col-xs-12 padding-none catalogs-with-sub">
        <div class="col-xs-12 padding-none">
            <?php $i = 0; foreach($parent[0]['subcat'] as $category): ?>
                <?php if($i%4 == 0 && $i!=0) echo '</div><div class="col-xs-12 padding-none">'; ?>
                <?php $i++ ?>
                <div class="block-div col-xs-3 padding-none">
                    <div class="title-div"><?php
                        if(!empty($category['icon'])) echo "<div class=\"icon\"><img src=\"", Yii::$app->request->baseUrl,"/",$category['icon'],"\"/></div>"; ?>
                        <?php echo Html::a($category['name'], \yii\helpers\Url::to(['catalog/index','cat' => $category['id']]), ['class' => 'link ' . (empty($category['icon']) ? '' : 'big-padding-left')]) ?></div>
                    <?php if(empty($category['subcat'])): ?>
                        <div class="child-subcat link">
                            <?php echo Html::a(Yii::t('app', 'catalog.incat'), ['catalog/index','cat' => $category['id']]) ?>
                        </div>
                    <?php endif; ?>
                    <?php foreach($category['subcat'] as $sub): ?>
                        <div class="child-subcat link">
                            <?php echo Html::a($sub['name'], ['catalog/index','cat' => $sub['id']]) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

views/catalog/catalog-index-level-1.php
<?php
//require_once 'catalog-index-level-1_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'catalog-index-2']);
$this->title = $template->fstitle;
//$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>

views/catalog/catalog-index-level-2_old.php
<?php

use yii\helpers\Html;
use app\models\CatalogRu;
use yii\bootstrap\ButtonDropdown;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CatalogSearchRu */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $subcat int */

$prices = ['BYR', 'RUR', 'USD'];

/** @var CatalogRu $catInfo */
$catInfo = CatalogRu::find()->where(['ficatalog_id' => $subcat])->andWhere(['fivisible' => 1])->one();

$this->title = $catInfo->fsname;

$items = Yii::$app->db->createCommand('SELECT
                                            i.*
                                        FROM
                                            items i
                                        /*LEFT JOIN params_values pv ON pv.fiitem_id = i.fiitem_id
                                        LEFT JOIN params_cat pc ON pv.fiparam_id = pc.fiparam_id*/
                                        WHERE
                                            i.fiitem_id IN(
                                                SELECT
                                                    fiitem_id
                                                FROM
                                                    catalog_items
                                                WHERE
                                                    ficatalog_id = :ficatalogid
                                            )
                                        ORDER BY fiorder',['ficatalogid' => $subcat])->queryAll();

$podcats = Yii::$app->db->createCommand('SELECT * FROM catalog_ru WHERE fiparent_catalog_id = :parentid', ['parentid' => $subcat])->queryAll();

$podItems = [];
$searchAr = [0];

foreach($podcats as $pod) {
    $podItems[$pod['ficatalog_id']] = [
        'id'       => $pod['ficatalog_id'],
        'name'     => $pod['fsname'],
        'elements' => [],
    ];
    $searchAr[] = (int)$pod['ficatalog_id'];
}

$itemsPodcats = Yii::$app->db->createCommand('SELECT
                                            i.*, ci.ficatalog_id as cat
                                        FROM
                                            items i
                                        /*LEFT JOIN params_values pv ON pv.fiitem_id = i.fiitem_id*/
                                        INNER JOIN catalog_items ci ON i.fiitem_id = ci.fiitem_id
                                        WHERE
                                            i.fiitem_id IN(
                                                SELECT
                                                    fiitem_id
                                                FROM
                                                    catalog_items
                                                WHERE
                                                    ficatalog_id IN (' . implode(',', $searchAr) . ')
                                            )
                                        ORDER BY fiorder')->queryAll();

foreach($itemsPodcats as $item) {
    $podItems[$item['cat']]['elements'][] = $item;
}

// print_r($items);

$js = <<< JS

$(function() {

var current = null;

$('#show-info').on('show.bs.modal', function() {

    $('#show-info .modal-body').css({'min-height' : $('#show-info .properties').height() + $('.modal-body .pictures').height() + 35});
    $('#show-info .modal-body .properties .image').css({'padding-top': ($('#show-info .properties').height()-$('#show-info .properties .image').height())/2 });

    $('#show-info .properties .image').hide();
    window.setTimeout(function() {
        $('#show-info .modal-body').css({'min-height' : $('#show-info .properties').height() + $('.modal-body .pictures').height() + 35});
        $('#show-info .modal-body .properties .image').css({'padding-top': ($('#show-info .properties').height()-$('#show-info .properties .image').height())/2 });
        $('#show-info').modal('handleUpdate');
    }, 250);
    window.setTimeout(function() {
        $('#show-info .modal-body').css({'min-height' : $('#show-info .properties').height() + $('.modal-body .pictures').height() + 35});
        $('#show-info').modal('handleUpdate');
    }, 500);
    window.setTimeout(function() {
        $('#show-info .modal-body').css({'min-height' : $('#show-info .properties').height() + $('.modal-body .pictures').height() + 35});
        $('#show-info').modal('handleUpdate');
    }, 1000);
    $('#show-info .properties .image').show();
});

$('#show-info').on('click', 'div.left', function() {
    var self = $('.item-one[data-id=' + current + ']');
    self = self.prev('.item-one');
    if(!self.length) {
        self = $('.item-one:last');
    }
    self.find('.show-more').click();
});

$('#show-info').on('click', 'div.right', function() {
    var self = $('.item-one[data-id=' + current + ']');
    self = self.next('.item-one');
    if(!self.length) {
        self = $('.item-one:first');
    }
    self.find('.show-more').click();
});

$('.catalogs-items .item-one').on('click', '.show-more', function() {
    current = $(this).closest('.item-one').data('id');
    /*console.log($(this).closest('.item-one').data('id'))*/
    $.post('%URL%', {id : $(this).closest('.item-one').data('id')})
        .done(function(data) {
            $('#show-info .modal-content .modal-body').html(data);
            var item = $.parseJSON($('#show-info .dialog-data').html());
            $('#show-info .modal-header span.title')
                .remove();
            $('<span/>')
                .addClass('title')
                .text(item['fsitem_name'])
                .prependTo($('#show-info .modal-header'));
            /*console.log(item);*/
            $('#show-info .properties .image').hide();
            $('#show-info').modal();
        });
});

$('.catalogs-items .item-one').on('click', '.description a', function() {
    /*console.log($(this).closest('.item-one').data('id'))*/
    if(!$(this).data('id')) {
        return false;
    }
    current = $(this).closest('.item-one').data('id');
    $.post('%URL%', {id : $(this).data('id')})
        .done(function(data) {
            $('#show-info .modal-content .modal-body').html(data);
            var item = $.parseJSON($('#show-info .dialog-data').html());
            $('#show-info .modal-header span.title')
                .remove();
            $('<span/>')
                .addClass('title')
                .text(item['fsitem_name'])
                .prependTo($('#show-info .modal-header'));
            /*console.log(item);*/
            $('#show-info .properties .image').hide();
            $('#show-info').modal();
        });
});

$('.catalogs-items .item-one').on('click', '.btn-group .dropdown-menu li', function() {
    var price = $(this).data('price');
    var name = $(this).text();
    $(this).closest('.btn-group').find('.btn').html(name + ' <span class="caret"></span>');
    $(this).closest('.price-cell').find('.number').text(price);
});

$('[data-toggle="tooltip"]').tooltip();

});

JS;

$js = str_replace('%URL%', \yii\helpers\Url::to(['catalog/get-item']), $js);

$this->registerJs($js);

?>
<?php echo $this->render('/catalog/breadcrumb', ['breadcrumb' => $breadCrumbs]) ?>
<?php
    $modal = \yii\bootstrap\Modal::begin(['id' => 'show-info']);
    $modal->end();
?>
<div class="catalog-subcats">
    <div class="col-xs-12 padding-none general-titles center-block">
        <h2><?php echo $this->title ?></h2>
    </div>
    <?php if(strlen($catInfo->fsdestination) || strlen($catInfo->fswork) || strlen($catInfo->fsuse)): ?>
    <div class="col-xs-12 padding-none cat-desc">
        <?php if(strlen($catInfo->fsdestination)): ?>
        <div class="col-xs-12 padding-none">
            <div class="col-xs-12 padding-none title">Назначение</div>
            <div class="col-xs-12 padding-none desc"><?php echo $catInfo->fsdestination ?></div>
        </div>
        <?php endif; ?>
        <?php if(strlen($catInfo->fswork)): ?>
        <div class="col-xs-12 padding-none">
            <div class="col-xs-12 padding-none title">Принцип работы</div>
            <div class="col-xs-12 padding-none desc"><?php echo $catInfo->fswork ?></div>
        </div>
        <?php endif; ?>
        <?php if($catInfo->fsuse): ?>
        <div class="col-xs-12 padding-none">
            <div class="col-xs-12 padding-none title">Применение</div>
            <div class="col-xs-12 padding-none desc"><?php echo $catInfo->fsuse ?></div>
        </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="col-xs-12 padding-none catalogs-items">
        <?php foreach($podItems as $podcats): ?>
            <div class="col-xs-12 padding-none podcats-element">
                <div class="elem">
                    <span class="title"><?php echo $podcats['name'] ?></span>
                    <div class="line"><div class="inner"></div></div>
                </div>
            </div>
            <div class="col-xs-12 padding-none">
            <?php foreach($podcats['elements'] as $item): ?>
                <?php if(!empty($item['fsitem_before_text'])): ?>
                    <div class="col-xs-12 padding-none sub-item-desc">
                        <?php echo $item['fsitem_before_text'] ?>
                    </div>
                <?php endif; ?>
                <?php echo $this->render('item', ['item' => $item, 'prices' => $prices]) ?>
            <?php endforeach; ?>
            </div>
        <?php endforeach; ?>

        <?php foreach($items as $item): ?>
            <?php if(!empty($item['fsitem_before_text'])): ?>
                <div class="col-xs-12 padding-none sub-item-desc">
                    <?php echo $item['fsitem_before_text'] ?>
                </div>
            <?php endif; ?>
            <?php echo $this->render('item', ['item' => $item, 'prices' => $prices]) ?>
        <?php endforeach; ?>
    </div>
</div>

views/catalog/catalog-menu.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/** @var \app\components\SiteView $this */
/** @var array $catalogs[] */
/** @var int $active */

?>
<div class="col-xs-12 padding-none general-titles">
    <?php foreach ($catalogs as $row): ?>
        <div class="col-md-2 col-xs-6  col-sm-4 padding-none big-cats <?php if($active == $row['id']) { echo "active"; } ?>">
            <div class="col-xs-12 padding-none image">
                <?php echo Html::tag( strlen($row['link']) ? 'noindex' : 'span', Html::a(Html::img(Yii::$app->request->baseUrl . '/' . $row['big-image']), strlen($row['link']) ? $row['link'] : Url::to(['catalog/index','cat' => $row['id']]), strlen($row['link']) ? ['target' => 'blank','rel'=>'nofollow'] : [])) ?>
            </div>
            <div class="col-xs-12 padding-none">
                <?php echo strlen($row['link']) ? Html::tag('noindex',Html::a($row['name'], $row['link'], ['target' => 'blank','rel'=>'nofollow'])) : Html::a($row['name'], Url::to(['catalog/index','cat' => $row['id']])) ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>

views/catalog/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\CatalogRu */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => Yii::t('app','Catalog Ru'),
]);
?>
<div class="catalog-ru-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/catalog/custom_template.php
<?php eval("?>" . $template . "<?php ");