models/Items.php
<?php

namespace app\models;

use Yii;
use yii2tech\ar\linkmany\LinkManyBehavior;

/**
 * This is the model class for table "items".
 *
 * @property string $fiitem_id
 * @property string $fsitem_name
 * @property string $fsitem_old_desc
 * @property string $fsitem_picture
 * @property string $fsitem_small_desc
 * @property string $fspassport
 * @property string $fsparams_array
 * @property integer $fianother_customer
 * @property string $fsitem_customer
 * @property integer $fitemplate_id
 * @property integer $fiitem_catalog_id
 * @property string $fsarticle
 * @property string $fsprice_rur
 * @property string $fsprice_usd
 * @property string $fsprice_byr
 * @property integer $fiorder
 * @property string $fdcreate_date
 * @property string $finew
 * @property string $fsseo
 *
 * @property ItemsPictures[] $itemsPictures
 * @property ParamsValues[] $paramsValues
 * @property Items[] $similarItems
 */
class Items extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'items';
    }

    public function behaviors()
    {
        return [
            'linkSimilarItemsBehavior' => [
                'class' => LinkManyBehavior::className(),
                'relation' => 'similarItems', // relation, which will be handled
                'relationReferenceAttribute' => 'similarItemIds', // virtual attribute, which is used for related records specification
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fsitem_name'], 'required'],
            [['fsitem_old_desc', 'fsitem_small_desc', 'fsparams_array', 'fsitem_before_text', 'fsseo', 'fsitem_bottom_text', 'fsitem_passport_text'], 'string'],
            [['fianother_customer', 'fitemplate_id', 'fiitem_catalog_id', 'fiorder', 'finew'], 'integer'],
            [['fsitem_name', 'fspassport', 'fsitem_picture', 'fsitem_customer'], 'string', 'max' => 255],
            [['fsarticle', 'fsprice_rur', 'fsprice_usd', 'fsprice_byr', 'fdcreate_date'], 'string', 'max' => 30],
            [['fsitem_name'], 'unique'],
            [['fsitem_bottom_text_en', 'fsitem_small_desc_en','fsseo_en'], 'string'],
            ['similarItemIds', 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'fiitem_id' => Yii::t('app', 'Внутренний номер товара'),
            'fsitem_name' => Yii::t('app', 'Название товара'),
            'fsitem_old_desc' => Yii::t('app', 'Описание в старом формате'),
            'fsitem_picture' => Yii::t('app', 'Картинка товара'),
            'fsitem_small_desc' => Yii::t('app', 'Краткое описание'),
            'fsparams_array' => Yii::t('app', 'Fsparams Array'),
            'fianother_customer' => Yii::t('app', 'Признак конкурента'),
            'fsitem_customer' => Yii::t('app', 'Производитель'),
            'fitemplate_id' => Yii::t('app', 'Внутренний номер шаблона'),
            'fiitem_catalog_id' => Yii::t('app', 'Fiitem Catalog ID'),
            'fspassport' => Yii::t('app', 'fspassport'),
            'fsarticle' => Yii::t('app', 'Fsarticle'),
            'fsprice_rur' => Yii::t('app', 'Fsprice Rur'),
            'fsprice_usd' => Yii::t('app', 'Fsprice Usd'),
            'fsprice_byr' => Yii::t('app', 'Fsprice Byr'),
            'fiorder' => Yii::t('app', 'Fiorder'),
            'fsitem_before_text' => Yii::t('app', 'fsitem_before_text'),
            'fdcreate_date' => Yii::t('app', 'fdcreate_date'),
            'finew' => Yii::t('app', 'finew'),
            'fsseo' => Yii::t('app', 'fsseo'),
            'fisale_id' => Yii::t('app', 'Sales'),
            'fsitem_bottom_text' => Yii::t('app', 'fsitem_bottom_text'),
            'fsitem_passport_text' => Yii::t('app', 'Паспорт изделия (Описание)'),
            'fsitem_bottom_text_en' => Yii::t('app', 'fsitem_bottom_text') . ' En',
            'fsitem_small_desc_en' => Yii::t('app', 'Краткое описание') . ' En',
            'fsseo_en' => Yii::t('app', 'fsseo') . ' En',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParamsValues()
    {
        return $this->hasMany(ParamsValues::className(), ['fiitem_id' => 'fiitem_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainCatalog()
    {
        return $this->hasOne(CatalogRu::className(), ['ficatalog_id' => 'ficatalog_id'])->viaTable('catalog_items', ['fiitem_id' => 'fiitem_id']);
    }

    public function getSimilarItems()
    {
        return $this
            ->hasMany(Items::className(), ['fiitem_id' => 'similar_item_id'])
            ->viaTable('{{%items__similar}}', ['item_id' => 'fiitem_id'])
        ;
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ItemsSearch;
use app\models\NewsSearch;
use app\models\CatalogSearchRu;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDownloads() {
        return $this->render('downloads');
    }

    public function actionCooperation()
    {
        $result = false;
        if(Yii::$app->request->isPost) {

            $body = '';
            $body .= 'Имя: ' . "\t" . Yii::$app->request->post('name') . "\n";
            $body .= 'Телефон: ' . "\t" . Yii::$app->request->post('phone') . "\n";
            $body .= 'Страна: ' . "\t" . Yii::$app->request->post('country') . "\n";
            $body .= 'Город: ' . "\t" . Yii::$app->request->post('town') . "\n";
            $body .= 'Email: ' . "\t" . Yii::$app->request->post('mail') . "\n";
            $body .= 'Комментарий: ' . "\t" . Yii::$app->request->post('comment') . "\n";

            $type = Yii::$app->request->post('type');

            try {
                $result = Yii::$app->mailer->compose()
                    ->setTo('2258769@tde-fif.ru')
                    ->setFrom([Yii::$app->request->post('mail') => Yii::$app->request->post('name')])
                    ->setSubject('Заявка на ' . ($type == 'diller' ? 'дилера' : 'инсталлятора'))
                    ->setTextBody($body)
                    ->send();
            }
            catch(Exception $ex) {
                $result = false;
            }

        }
        return $this->render('cooperation', ['result' => $result]);
    }

    public function actionCertificats() {
        return $this->render('sertification');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSearch($query)
    {
        $searchModel = new ItemsSearch();
        @$s['ItemsSearch']['q']=$query;
        $dataProvider = $searchModel->search($s);

        $searchModel2 = new NewsSearch();
        @$s['NewsSearch']['q']=$query;
        $dataProvider2 = $searchModel2->search($s);

        $searchModel3 = new CatalogSearchRu();
        @$s['CatalogSearchRu']['q']=$query;
        $dataProvider3 = $searchModel3->search($s);

        if(Yii::$app->request->isAjax) {
            $response=[];
            if (($search=$dataProvider->getModels())!==null)
                foreach ($search as $row) {
                    $response[]=[
                        'link'=>\yii\helpers\Url::to(['catalog/items', 'id' => $row['fiitem_id']]),
                        'label'=>$row['fsitem_name'],
                        'value'=>$row['fsitem_name'],
                        'query'=>$query,
                    ];
                }
                return json_encode($response);
        } else {
            return $this->render('search',[
                'searchModel'=>$searchModel,
                'dataProvider'=>$dataProvider,
                'dataProvider2'=>$dataProvider2,
                'dataProvider3'=>$dataProvider3,
            ]);
        }
    }
}

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

views/site/cooperation.php
<?php
use app\models\SiteTemplates;
use yii\bootstrap\Modal;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/cooperation']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
return;
?>

<?php
use yii\helpers\Html;
use app\models\Sertificats;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var bool $result */

$this->title = Yii::t('app', 'cooperation.title');

$js = <<< JS

$(function() {

    $('.select-type').on('click', '.coop-button', function() {
        $('.select-type span.active').removeClass('active');
        $(this).addClass('active');
        $('.form input[name=type]').val($(this).hasClass('diller') ? 'diller' : 'installer');
        $('.form p.form-title .active').removeClass('active');
        $('.form p.form-title').find('.' + $('.form input[name=type]').val()).addClass('active');
    });

    $('form').on('click', '.submit', function() {
        $.post($(location).attr('href'), $('form').serializeArray())
            .success(function() {
                alert('Запрос отправлен, ожидайте с вами свяжуться сотрудники компании');
                $('.modal').modal('hide');
            })
            .error(function() {
                alert('Проверьте введенные данные');
            });
        return false;
    });

});

JS;

$this->registerJs($js);

?>

<div class="distributors-index">
    <div class="padding-none col-xs-12 where-buy">
        <?php echo Yii::t('app', 'cooperation.title') ?>
    </div>
    <div class="col-xs-12 padding-none gray-buy">
        <?php echo Yii::t('app', 'cooperation.text') ?>
    </div>
    <br/>
    <div class="col-xs-12 padding-none cooperation center-block">
        <?php if($result): ?>
            <div class="col-xs-12 title" style="text-align: center;">
                <?php echo Yii::t('app', 'cooperation.success') ?>
            </div>
        <?php else: ?>
            <div class="col-xs-12 form">
                <div class="col-xs-12 title">
                    <?php echo Yii::t('app', 'cooperation.select.type') ?>
                </div>
                <div class="col-xs-12 select-type">
                    <div class="col-xs-6 padding-none"><span class="diller active coop-button"><?php echo Yii::t('app', 'cooperation.diller') ?></span></div>
                    <div class="col-xs-6 padding-none"><span class="installer coop-button"><?php echo Yii::t('app', 'cooperation.installer') ?></span></div>
                </div>
                <div class="col-xs-1"></div>
                <div class="col-xs-10 note packet">
                    <br/>
                    <span class="diller active"><?php echo Yii::t('app', 'cooperation.diller.text') ?></span>
                    <span class="installer"><?php echo Yii::t('app', 'cooperation.installer.text') ?></span>
                </div>
                <div class="col-xs-1"></div>

                <?php

                Modal::begin ( [
                    'header' => '',
                    'toggleButton' => [
                        'tag' => 'button',
                        'class' => 'btn submit',
                        'label' => Yii::t('app', 'cooperation.ticket'),
                    ]
                ] );

                $form = ActiveForm::begin([
                    'options' => ['class' => 'form-inline']
                ]) ?>
                <input type="hidden" name="type" value="diller" />
                <p class="form-title">
                    <span class="diller active"><?php echo Yii::t('app', 'cooperation.form.diller') ?></span>
                    <span class="installer"><?php echo Yii::t('app', 'cooperation.form.installer') ?></span>
                </p><br/>
                <div class="form-group">
                    <label class="col-sm-4 control-label padding-none centered"><?php echo Yii::t('app', 'cooperation.form.name') ?></label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" placeholder="<?php echo Yii::t('app', 'cooperation.form.name') ?>" name="name">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label padding-none centered"><?php echo Yii::t('app', 'cooperation.form.country') ?></label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" placeholder="<?php echo Yii::t('app', 'cooperation.form.country') ?>" name="country">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label padding-none"><?php echo Yii::t('app', 'cooperation.form.phone') ?></label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" placeholder="<?php echo Yii::t('app', 'cooperation.form.phone') ?>" name="phone">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label padding-none centered"><?php echo Yii::t('app', 'cooperation.form.town') ?></label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" placeholder="<?php echo Yii::t('app', 'cooperation.form.town') ?>" name="town">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label padding-none centered">Email</label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" placeholder="Email" name="mail">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-4 control-label padding-none"><?php echo Yii::t('app', 'cooperation.form.comment') ?></label>
                    <div class="col-sm-8">
                        <textarea name="comment" placeholder="<?php echo Yii::t('app', 'cooperation.form.comment') ?>" class="form-control"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="center-block">

                        <button class="btn submit"><?php echo Yii::t('app', 'cooperation.ticket') ?></button>
                    </div>
                </div>

                <?php $form->end(); ?>


                <?php Modal::end();?>
            </div>
        <?php endif; ?>
    </div>
</div>

views/site/cooperation_old.php
<?php
use yii\helpers\Html;
use app\models\Sertificats;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var bool $result */

$this->title = 'Сотрудничество';

$js = <<< JS

$(function() {

    $('.select-type').on('click', '.coop-button', function() {
        if($('form').is(':visible')) {
            $('form').slideUp();
        }
        $('.select-type span.active').removeClass('active');
        $(this).addClass('active');
        $('.form input[name=type]').val($(this).hasClass('diller') ? 'diller' : 'installer');
        $('.form .form-title span:visible').hide();
        $('.form .form-title span.' + ($(this).hasClass('diller') ? 'diller' : 'installer')).show();
        $('form').slideDown();
    });

});

JS;

$this->registerJs($js);

?>

<div class="distributors-index">
    <div class="padding-none col-xs-12 where-buy">
        Сотрудничество
    </div>
    <div class="col-xs-12 padding-none gray-buy">
        Компания «Евроавтоматика ФиФ производит широкий ассортимент релейной защиты и автоматики и реализует его через дилерскую сеть. Мы приглашаем к сотрудничеству торговые и инжиниринговые компании.
    </div>
    <br/>
    <div class="col-xs-12 padding-none cooperation center-block">
        <div class="col-xs-1"></div>
        <?php if($result): ?>
            <div class="col-xs-10 title" style="text-align: center;">
                Заявка сформирована и отправлена на рассмотрение.
            </div>
        <?php else: ?>
        <div class="col-xs-10 form">
            <div class="col-xs-12 title">
                Выберите интересующий Вас тип сотрудничества и заполните заявку:
            </div>
            <div class="col-xs-12 select-type">
                <span class="diller coop-button">Дилер, дистрибьютор компании Евроавтоматика ФиФ</span>
                или
                <span class="installer coop-button">Авторизованный инсталлятор систем <a href="http://fhome.by/" target="_blank">F&Home</a></span>
            </div>
            <div class="col-xs-12 note packet">
                <br/>Продажа продукции торговой марки «F&F» Условия сотрудничества можно обсудить с заместителем начальника отдела продаж компании после заполнения Заявки
            </div>
            <?php $form = ActiveForm::begin([
                'options' => [
                    'style' => 'display:none;',
                ]
            ]) ?>
            <input type="hidden" name="type" value="diller" />
            <div class="col-xs-12 form-title">
                <span class="diller">Заявка на дилера</span>
                <span class="installer" style="display: none;">Заявка на инсталлятора</span>
            </div>
            <div class="col-xs-6">
                <input type="text" class="form-control" placeholder="Ваше имя*" name="name">
            </div>
            <div class="col-xs-6">
                <input type="text" class="form-control"  placeholder="Телефон с кодом страны" name="phone">
            </div>
            <div class="col-xs-6">
                <input type="text"  class="form-control"  placeholder="Страна" name="country">
            </div>
            <div class="col-xs-6">
                <input type="text"  class="form-control"  placeholder="Город" name="town">
            </div>
            <div class="col-xs-12">
                <input type="text" class="form-control" placeholder="Email" name="mail">
            </div>
            <div class="col-xs-12">
                <textarea name="comment" class="form-control" placeholder="Комментарий, если необходимо"></textarea>
            </div>
            <div class="col-xs-12">
                <button class="btn submit">Отправить заявку</button>
            </div>
            <?php $form->end(); ?>
        </div>
        <?php endif; ?>
        <div class="col-xs-1"></div>
    </div>
</div>

views/site/downloads.php
<?php
//require_once 'downloads_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/downloads']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>

views/site/downloads_old.php
<?php
use yii\helpers\Html;
use app\models\Sertificats;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Tabs;
use yii\data\ActiveDataProvider;
use app\models\PublicationFiles;
use yii\widgets\ListView;
use app\models\Publications;

/* @var $this yii\web\View */
/* @var bool $result */

$this->title = Yii::t('app', 'down.title');

$js = <<< JS

$(function() {

});

JS;

$this->registerJs($js);

?>

<div class="distributors-index download">
    <div class="padding-none col-xs-12 where-buy">
        <?php echo Yii::t('app', 'down.title') ?>
    </div>
<?php

$query = Publications::find()->where(['fitype' => 1]);

$provider = new ActiveDataProvider([
    'query' => $query,
    'pagination' => [
        'pageSize' => 99999,
    ],
]);

$publications = ListView::widget([
    'dataProvider' => $provider,
    'itemView' => '/publications/publication',
    'options' => ['class' => 'list-view'],
    'itemOptions' => [
        'class' => 'block-item',
    ],
    'summaryOptions' => [
        'style' => 'display:none;'
    ],
]);

$queryCat = Publications::find()->where(['fitype' => 0]);

$providerCat = new ActiveDataProvider([
    'query' => $queryCat,
    'pagination' => [
        'pageSize' => 99999,
    ],
]);

$publicationsCat = ListView::widget([
    'dataProvider' => $providerCat,
    'itemView' => '/publications/publication-cat',
    'options' => ['class' => 'list-view'],
    'itemOptions' => [
        'class' => 'block-item',
    ],
    'summaryOptions' => [
        'style' => 'display:none;'
    ],
]);

echo Tabs::widget ( [
    'items' => [
        [
            'label' => Yii::t('app','down.cat'),
            'content' => $publicationsCat,
            'active' => true
        ],
        [
            'label' => Yii::t('app','down.pub'),
            'content' => $publications
        ],
    ]
] );

?>
    </div>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = 'Ой ошибочка';
?>
<div class="site-error">

    <div class="col-xs-12 padding-none">
        <div class="col-xs-6 padding-none">
            <h1>Упсссс! <?php echo @$exception->statusCode ?></h1>
            <?php if(404 == @$exception->statusCode): ?>
            <span class="gray">Не можем найти страницу которую вы<br/>
                запросили, не расстраивайтесь, а лучше:
            </span><br/>
            <?php else: ?>
                <span class="gray"><?php echo $exception->getMessage() ?></span><br/>
            <?php endif; ?>
            <span class="links">
                <?php echo Html::a('Почитайте о нашей компании', ['site/about']) ?><br/>
                <?php echo Html::a('Посмотрите каталог товаров', ['catalog/index']) ?><br/>
                <?php echo Html::a('Напишите нам', 'mailto:info@tde-fif.ru') ?><br/>
            </span>
        </div>
        <div class="col-xs-6 padding-none">
            <?php echo Html::img(Yii::$app->request->baseUrl . '/image/site/404.png') ?>
        </div>
    </div>

</div>

views/site/index.php
<?php
//require_once 'index_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/index']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>

views/site/item-search.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ButtonDropdown;

/** var array $item */

?>
<div class="col-xs-12 item-new-one padding-none <?php if($item['fisale_id']) echo "sale"?>" data-id="<?php echo $item['fiitem_id'] ?>">

    <?php
        $itemValues = @$itemsValues[$item['fiitem_id']];
        if(empty($itemValues)) {
            $itemValues = [];
        }
        $itemValues = array_map(
          function($el) {
            return @array_values($el)[0];
        }, $itemValues);
    ?>

    <div class="hidden-info" style="display: none;"><?php echo json_encode($itemValues) ?></div>
    <div class="col-xs-12 padding-none">
        <div class="desc col-xs-12 padding-none" data-toggle="tooltip" data-placement="top" title="<?php echo $item['fsitem_small_desc'] ?>">
            <div class="description">
                <p class="title"><?php echo Html::a(@$item->mainCatalog->fsname.' '.$item['fsitem_name'], \yii\helpers\Url::to(['catalog/items', 'id' => $item['fiitem_id']])) ?></p>
                <?php echo $item['fsitem_small_desc'] ?>
                    <?php /*if(!empty($itemsValues[$item['fiitem_id']])) {
                        $index = 0;
                        foreach(@$itemsValues[$item['fiitem_id']] as $id => $params) {
                            echo '<div class="col-xs-9 param-name padding-none"><div class="dots"></div><div class="name">',array_keys($params)[0], '</div></div><div class="col-xs-3 param-value padding-none">', array_values($params)[0], '</div>';
                            $index++;
                            if($index>=5) {
                                break;
                            }
                        }
                    }*/
                ?>
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Вход';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста введите логин и пароль:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/sertification.php
<?php
//require_once 'sertification_old.php'; return;
use app\models\SiteTemplates;

/** @var SiteTemplates $template */
$template = SiteTemplates::findOne(['fscode' => 'site/certificats']);
$this->title = $template->fstitle;
$this->seoFields = $template->fstemplate_seo;
eval("?>" . $template->fstemplate_code . "<?php ");
?>